# Generated by Django 5.2.14 on 2026-05-06 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(blank=True, default='', help_text="Self-identified pronouns, e.g. 'she/her', 'they/them'.", max_length=64)),
                ('department', models.CharField(blank=True, default='', help_text='Department affiliation key. Validated against settings.REGISTRATION_DEMOGRAPHICS_DEPARTMENTS.', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The learner whose demographics these are.', on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner demographics',
                'verbose_name_plural': 'Learner demographics',
            },
        ),
    ]
